
# tap repositories and their packages

## caskroom/cask
tap caskroom/cask
brew brew-cask
cask 1password
cask adobe-creative-cloud
cask adobe-illustrator-cc
cask adobe-photoshop-cc
cask alfred
cask appcleaner
cask bettertouchtool
cask chromecast
cask cleanarchiver
cask coteditor
cask diskwave
cask dropbox
cask filezilla
cask firefox
cask framer-studio
cask glueprint
cask google-chrome
cask google-drive
cask insomniax
cask java
cask keyboard-cleaner
cask language-switcher
cask libreoffice
cask mou
cask principle
cask selfcontrol
cask sequel-pro
cask skype
cask sourcetree
cask spotify
cask techstoreclub-simple-comic
cask the-unarchiver
cask totalfinder
cask totalterminal
cask tunnelbear
cask vagrant
cask virtualbox
cask vlc

## caskroom/versions
tap caskroom/versions
cask google-chrome-canary
cask scansnap-manager-s1300
cask sublime-text3

## homebrew/dupes
tap homebrew/dupes

## homebrew/versions
tap homebrew/versions
brew maven2

## josegonzalez/php
tap josegonzalez/php
brew php56

## rcmdnk/file
tap rcmdnk/file
brew brew-file

# Other Homebrew packages
brew ansible
brew autoconf
brew automake
brew cabal-install
brew cairo
brew cask
brew casperjs --devel
brew chruby
brew clamav
brew cloog
brew cmake
brew composer
brew coreutils
brew ctags
brew czmq
brew emacs
brew fish
brew fontconfig
brew fontforge
brew freetype
brew gcc
brew gdbm
brew gettext
brew ghc
brew git
brew git-lfs
brew glib
brew gmp
brew gobject-introspection
brew harfbuzz
brew hub
brew icu4c
brew imagemagick
brew isl
brew jpeg
brew jpeg-turbo
brew libffi
brew libmpc
brew libpng
brew libsodium
brew libtiff
brew libtool
brew libxml2
brew libyaml
brew makedepend
brew mongodb
brew mpfr
brew mysql
brew nasm
brew node
brew openssl
brew pandoc
brew pango
brew pcre
brew peco
brew pkg-config
brew pngquant
brew postgresql
brew pstree
brew putty
brew pyenv
brew pyenv-virtualenv
brew python
brew rbenv
brew readline
brew rename
brew ruby
brew ruby-build
brew sbt
brew sqlite
brew the_silver_searcher
brew tomcat
brew unixodbc
brew wget
brew xz
brew z
brew zeromq
brew zlib

# App Store applications
appstore Evernote
appstore GarageBand
appstore Keynote
appstore LINE
appstore Numbers
appstore Sketch
appstore Skitch
appstore Slack
appstore Xcode
